
spring:
  datasource:
    url: jdbc:postgresql://db:5432/university_courses
    username: ashraful
    password: secretpassword
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        jdbc:
          time_zone: UTC
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect